default_agent: pipeline_integrity_agent
agents:
  pipeline_integrity_agent:
    name: pipeline_integrity_agent
    language: python
    node_version: '20'
    entrypoint: /home/ubuntu/awshack/agent/agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /home/ubuntu/awshack/agent
    aws:
      execution_role: arn:aws:iam::211125430374:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-77b5f1174b
      execution_role_auto_create: false
      account: '211125430374'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-211125430374-us-west-2
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: pipeline_integrity_agent-1ZMVK49mbl
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:211125430374:runtime/pipeline_integrity_agent-1ZMVK49mbl
      agent_session_id: a426a0bb-67b2-4b6a-b700-deb1398c4006
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: pipeline_integrity_agent_mem-P4sZoe9KdC
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:211125430374:memory/pipeline_integrity_agent_mem-P4sZoe9KdC
      memory_name: pipeline_integrity_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
